before:
  hooks:
    - go mod tidy
archives:
  - format: zip
builds:
  - binary: terraform-provider-serverless_v{{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
      - linux
      - windows
changelog:
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"
      - "^docs:"
      - "^test:"
env:
  - GO111MODULE=on
