service: sls-provider

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x

package:
  include:
    # Root level
    - "!*"
    - "package.json"
    # Source directories
    - "!aws/**"
    - "!terraform"
    - "!terraform/**"
    - "!.terraform-serverless"
    - "!.terraform-serverless/**"
    - "!**/.terraform"
    - "!**/.terraform/**"
    # General exclusions
    - "!**/.DS_Store"
    # Dependencies
    - "!node_modules/aws-sdk"
    - "!node_modules/aws-sdk/**"
    - "!**/node_modules/aws-sdk"
    - "!**/node_modules/aws-sdk/**"
    - "!**/node_modules/*/CHANGELOG.md"
    - "!**/node_modules/*/HISTORY.md"
    - "!**/node_modules/*/LICENSE"
    - "!**/node_modules/*/README.md"
    - "index.js"

functions:
  currentTime:
    handler: index.handler
    events:
      - http:
          path: ping
          method: get
